export const CURRENT_USER_INFO = process.env.NODE_ENV === 'production'
    ? 'CARD$COMMON$GET_CURRENT_USER_INFO$XML'
    : 'CARD$COMMON$GET_CURRENT_USER_INFO_TEST$XML';

export const MEETING_HEADER = 'CARD$MEETING$HEADER$XML';
export const MEETING_SEARCH = 'CARD$MEETING$SEARCH$XML';
export const MEETING_QUESTIONS_LIST = 'CARD$MEETING$QUESTIONS_LIST$XML';

export const QUESTION_HEADER = 'CARD$QUESTION$HEADER$XML';
export const QUESTION_CARD = 'CARD$QUESTION$CARD$XML';
export const QUESTION_HISTORY = 'CARD$QUESTION$HISTORY$XML';
